### ISSUE TITLE
ZSI Requirement ?

### ISSUE THREAD

**Issue by amittamari** [Zenchreal/rising-eagle-soap#1]
I get this error when trying to run server.py:

`Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from soap.StorageServer_server import *
  File "X:\Misc\rising-eagle-soap-master\soap\StorageServer_server.py", line 9, in <module>
    from ZSI.schema import GED, GTD
ImportError: No module named ZSI.schema`

**Comment by amittamari** [comment]
Nevermind, I missed the docker file.
